include "./tools.conf";
include "./utils/*.conf";
include "./filters/*.conf";

function prefix_whitelist (prefix set prefix_whitelist) {
  if net !~ prefix_whitelist then {
    print bgp_path.first, ": filtered ", net, "are not in prefix_whitelist";
    reject;
  }
}

function prefix_blacklist (prefix set prefix_blacklist) {
  if net ~ prefix_blacklist then {
    print bgp_path.first, ": filtered ", net, "are in prefix_blacklist";
    reject;
  }
}

function peer_setup_import (string peer_type; int input_quality) {
  if !(peer_type = "upstream" || peer_type = "downstream" || peer_type = "peer" || peer_type = "ixrs" || peer_type = "ibgp") then {
    # print "peer_setup: unknown type ", peer_type;
    reject "peer_setup: unknown type ", peer_type;
  }

  if (net.len > 48) then reject;
  if (net.len < 8) then reject;

  if peer_type = "ibgp" then {
    if !peer_setup_import_ibgp(input_quality) then {
      reject;
    }
  } else if peer_type = "upstream" then {
    if !peer_setup_import_upstream(input_quality) then {
      reject;
    }
  } else if peer_type = "downstream" then {
    if !peer_setup_import_downstream(input_quality) then {
      reject;
    }
  } else if peer_type = "ixrs" then {
    if !peer_setup_import_ixrs(input_quality) then {
      reject;
    }
  } else if peer_type = "peer" then {
    if !peer_setup_import_peer(input_quality) then {
      reject;
    }
  }

  accept;
}

function peer_setup_export (string peer_type; int neighbor_asn) {
  if !(peer_type = "upstream" || peer_type = "downstream" || peer_type = "peer" || peer_type = "ixrs" || peer_type = "ibgp") then {
    # print "peer_setup: unknown type ", peer_type;
    reject "peer_setup: unknown type ", peer_type;
  }

  if (net.len > 48) then reject;
  if (net.len < 8) then reject;

  if peer_type = "ibgp" then {
    if !peer_setup_export_ibgp() then {
      reject;
    }
  } else if peer_type = "upstream" then {
    if !peer_setup_export_upstream(neighbor_asn) then {
      reject;
    }
  } else if peer_type = "downstream" then {
    if !peer_setup_export_downstream() then {
      reject;
    }
  } else if peer_type = "ixrs" then {
    if !peer_setup_export_ixrs() then {
      reject;
    }
  } else if peer_type = "peer" then {
    if !peer_setup_export_peer() then {
      reject;
    }
  }

  accept;
}
