function peer_setup_import_ibgp (int input_quality) {
  if bgp_large_community !~ [(SELF_ASN, 114514, *)] then {
    bgp_large_community.add((SELF_ASN, 114514, 1));
  }

  if net ~ BACKBONE_CIDR then {
    print "peer_setup: ", net, " is in backbone CIDR";
    return false;
  }

  int Q = setup_network_quality(input_quality);
  bgp_local_pref = 100 - Q;

  return true;
}

function peer_setup_export_ibgp () {
  if net ~ BACKBONE_CIDR then {
    print "peer_setup: ", net, " is in backbone CIDR";
    return false;
  }

  if source ~ [ RTS_BGP, RTS_STATIC ] then {
    return true;
  }

  return false;
}
