function peer_setup_import_ixrs (int input_quality) {
  bgp_large_community.add((SELF_ASN, 114514, 4));
  
  int Q = setup_network_quality(input_quality);
  bgp_local_pref = 200 - Q;

  return true;
}

function peer_setup_export_ixrs () {
  if bgp_large_community ~ [(SELF_ASN, 100001, 0)] then {
    return false;
  }

  bgp_large_community.delete([(SELF_ASN, 100001, *)]);

  if source ~ [ RTS_STATIC ] then {
    bgp_large_community.delete([(SELF_ASN, 114514, *)]);
    return true;
  }

  if (SELF_ASN, 114514, 1) ~ bgp_large_community then {
    bgp_large_community.delete([(SELF_ASN, 114514, *)]);
    return true;
  }

  if (SELF_ASN, 114514, 3) ~ bgp_large_community then {
    bgp_large_community.delete([(SELF_ASN, 114514, *)]);
    return true;
  }

  return false;
}
