function peer_setup_import_upstream (int input_quality) {
  bgp_large_community.add((SELF_ASN, 114514, 2));

  int Q = setup_network_quality(input_quality);
  bgp_local_pref = 190 - Q;

  return true;
}

function peer_setup_export_upstream (int neighbor_asn) {
  if (
    (SELF_ASN, 114514, 2) ~ bgp_large_community
    || (SELF_ASN, 114514, 4) ~ bgp_large_community
    || (SELF_ASN, 114514, 5) ~ bgp_large_community
  ) then {
    # 只导出下游和自己的路由
    return false;
  }

  bgp_large_community.delete([(SELF_ASN, 114514, *)]);

  if bgp_large_community !~ [(SELF_ASN, 100001, *)] then {
    bgp_large_community.delete([(SELF_ASN, 100001, *)]);
    bgp_large_community.delete([(SELF_ASN, 100002, *)]);
    return true;
  }

  if (SELF_ASN, 100001, neighbor_asn) ~ bgp_large_community then {
    bgp_large_community.delete([(SELF_ASN, 100001, *)]);
    bgp_large_community.delete([(SELF_ASN, 100002, *)]);
    return true;
  }

  return false;
}
