include "./vars.conf";
include "./kernel.conf";
include "./static.conf";
include "./functions/filters.conf";
include "./template/*";
include "./peers/*";
include "./ibgp/*";
# include "./collector/*";

protocol bfd bfd {
  interface "*" {
    interval 500ms;
  };
}

protocol bgp test6 {
  local as 150184;
  neighbor fd00:eb8d:db5e:2071:ffff:ffff:ffff:fffe as 65000;
  source address fd00:eb8d:db5e:2071::2;
  interface "jsbgp";

  ipv6 {
    export all;
    import none;
  };

  ipv4 {
    export none;
    import none;
  };
}

protocol bgp test4 {
  local as 150184;
  neighbor 6.255.255.2 as 65000;
  source address 6.255.255.1;
  interface "jsbgp";

  ipv6 {
    export none;
    import none;
  };

  ipv4 {
    table bgp4;

    export all;
    import none;
  };
}
