include "./vars.conf";
include "./kernel.conf";
include "./static.conf";
include "./functions/filters.conf";
include "./template/*";
include "./peers/*";
include "./ibgp/*";
# include "./collector/*";

# protocol bfd bfd {
#   interface "*" {
#     interval 500ms;
#   };
# }
