protocol kernel {
  scan time 20;

  ipv6 {
    import none;
    export filter {
      if proto ~ "C_AS*" then reject;
      if net ~ BACKBONE_CIDR then reject;

      # krt_prefsrc = SELF_ADDRESS;
      krt_prefsrc = 2406:840:e301:ff00::5353;
      accept;
    };
  };
}

protocol device {
  scan time 20;
}
