protocol kernel {
  scan time 20;

  ipv6 {
    import none;
    export filter {
      if net ~ BACKBONE_CIDR then reject;

      krt_prefsrc = SELF_ADDRESS;
      accept;
    };
  };
}

protocol device {
  scan time 20;
}
