protocol static {
  ipv6 {
    import all;
    export none;
  };

  route 2406:840:e301::/48 reject {
    bgp_large_community.add((SELF_ASN, 114514, 1));
  };

  route 2602:f9f6:400::/48 reject {
    bgp_large_community.add((SELF_ASN, 114514, 1));
  };

  route 2602:f9f6:401::/48 reject {
    bgp_large_community.add((SELF_ASN, 114514, 1));
  };
}