protocol bgp I_passive {
  local as 150184;
  neighbor range 2406:840:e300:ffee:3397::/80 as 150184;
  source address SELF_ADDRESS;
  graceful restart on;
  rr client;
  bfd on;
  passive;
  dynamic name "I_passive_idx";
  dynamic name digits 2;
  direct;

  ipv6 {
    next hop self;

    export filter {
      peer_setup_export("ibgp", 150184);
    };

    import filter {
      peer_setup_import("ibgp");
    };
  };
}
